const albums = [
  {
    id: 1,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "50",
    cover: "",
  },
  {
    id: 2,
    artist: "Matt Baldwin",
    name: "Paths of Ignition",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 3,
    artist: "The Beatles",
    name: "Rubber Soul",
    year: "1965",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 4,
    artist: "The Black Heart Procession",
    name: "Three",
    year: "2000",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 5,
    artist: "The Black Heart Procession",
    name: "Amore Del Tropico",
    year: "2002",
    notes: "",
    price: "100",
    cover: "",
  },

  {
    id: 6,
    artist: "The Black Heart Procession",
    name: "Six",
    year: "2009",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 7,
    artist: "Black Moth Super Rainbow",
    name: "Dandelion Gum",
    year: "2008",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 8,
    artist: "Black Sabbath",
    name: "Black Sabbath",
    year: "1970",
    notes: "This LP has the cover of Evil Woman on it.",
    price: "1000",
    cover: "",
  },
  {
    id: 9,
    artist: "Black Sabbath",
    name: "Master of Reality",
    year: "1971",
    notes: "this one is a little warped",
    price: "50",
    cover: "",
  },
  {
    id: 10,
    artist: "Black Sabbath",
    name: "Sabotage",
    year: "1975",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 11,
    artist: "David Bowie",
    name: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
    year: "1972",
    notes: "",
    price: "50",
    cover: "",
  },
  {
    id: 12,
    artist: "David Bowie",
    name: "Let's Dance",
    year: "1983",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 13,
    artist: "Broadcast",
    name: "Berbarian Sound",
    year: "2013",
    notes: "",
    price: "1000",
    cover: "",
  },
  {
    id: 14,
    artist: "Arthur Brown's Kingdome Come",
    name: "Journey",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 15,
    artist: "Ezra Buchla",
    name: "Heavy Axe",
    year: "2013",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 16,
    artist: "John Cale",
    name: "Guts",
    year: "1977",
    notes: "",
    price: "50",
    cover: "",
  },
  {
    id: 17,
    artist: "Can",
    name: "Tago Mago",
    year: "1971",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 18,
    artist: "Nick Cave and the Bad Seeds",
    name: "The First Born is Dead",
    year: "1985",
    notes: "no cover",
    price: "100",
    cover: "",
  },
  {
    id: 19,
    artist: "Nick Cave and the Bad Seeds",
    name: "The First Born is Dead",
    year: "1985",
    notes: "no cover",
    price: "100",
    cover: "",
  },
  {
    id: 20,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 21,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 22,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 23,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 24,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 25,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 26,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 27,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 28,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 29,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 30,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 31,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 32,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 33,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 34,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 35,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 36,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 37,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
];
