const albums = [
  {
    id: 1,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "50",
    cover: "/album-covers/Heavy-Axe.jpg",
  },
  {
    id: 2,
    artist: "Matt Baldwin",
    name: "Paths of Ignition",
    year: "1974",
    notes: "",
    price: "100",
    cover: "/album-covers/PathsOfIgnition.jpg",
  },
  {
    id: 3,
    artist: "The Beatles",
    name: "Rubber Soul",
    year: "1965",
    notes: "",
    price: "100",
    cover: "/album-covers/RubberSoul.png",
  },
  {
    id: 4,
    artist: "The Black Heart Procession",
    name: "Three",
    year: "2000",
    notes: "",
    price: "100",
    cover: "/album-covers/BHPThree.png",
  },
  {
    id: 5,
    artist: "The Black Heart Procession",
    name: "Amore Del Tropico",
    year: "2002",
    notes: "",
    price: "100",
    cover: "/album-covers/AmoreDelTropico.png",
  },

  {
    id: 6,
    artist: "The Black Heart Procession",
    name: "Six",
    year: "2009",
    notes: "",
    price: "100",
    cover: "/album-covers/BHPSix.png",
  },
  {
    id: 7,
    artist: "Black Moth Super Rainbow",
    name: "Dandelion Gum",
    year: "2008",
    notes: "",
    price: "100",
    cover: "/album-covers/DandelionGum.png",
  },
  {
    id: 8,
    artist: "Black Sabbath",
    name: "Black Sabbath",
    year: "1970",
    notes: "This LP has the cover of Evil Woman on it.",
    price: "1000",
    cover: "/album-covers/BlackSabbath.png",
  },
  {
    id: 9,
    artist: "Black Sabbath",
    name: "Master of Reality",
    year: "1971",
    notes: "this one is a little warped",
    price: "50",
    cover: "/album-covers/MasterOfReality.png",
  },
  {
    id: 10,
    artist: "Black Sabbath",
    name: "Sabotage",
    year: "1975",
    notes: "",
    price: "100",
    cover: "/album-covers/Sabotage.png",
  },
  {
    id: 11,
    artist: "David Bowie",
    name: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
    year: "1972",
    notes: "",
    price: "50",
    cover: "",
  },
  {
    id: 12,
    artist: "David Bowie",
    name: "Let's Dance",
    year: "1983",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 13,
    artist: "Broadcast",
    name: "Berbarian Sound",
    year: "2013",
    notes: "",
    price: "1000",
    cover: "",
  },
  {
    id: 14,
    artist: "Arthur Brown's Kingdome Come",
    name: "Journey",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 15,
    artist: "Ezra Buchla",
    name: "Heavy Axe",
    year: "2013",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 16,
    artist: "John Cale",
    name: "Guts",
    year: "1977",
    notes: "",
    price: "50",
    cover: "",
  },
  {
    id: 17,
    artist: "Can",
    name: "Tago Mago",
    year: "1971",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 18,
    artist: "Nick Cave and the Bad Seeds",
    name: "The First Born is Dead",
    year: "1985",
    notes: "no cover",
    price: "20",
    cover: "",
  },
  {
    id: 19,
    artist: "Patsy Cline",
    name: "Always",
    year: "1980",
    notes: "",
    price: "20",
    cover: "",
  },
  {
    id: 20,
    artist: "Leonard Cohen",
    name: "Live Songs",
    year: "1973",
    notes: "",
    price: "30",
    cover: "",
  },
  {
    id: 21,
    artist: "Ornette Coleman",
    name: "Ornette on Tenor",
    year: "1962",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 22,
    artist: "Alice Coltrane",
    name: "Ptah the el Daoud",
    year: "1970",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 23,
    artist: "The Cure",
    name: "Kiss Me Kiss Me Kiss Me",
    year: "1987",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 24,
    artist: "Dark Mark vs Skeleton Joe",
    name: "Dark Mark vs Skeleton Joe",
    year: "2021",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 25,
    artist: "Miles Davis",
    name: "Sketches of Spain",
    year: "1960",
    notes: "",
    price: "100",
    cover: "/album-covers/SketchesOfSpain.png",
  },
  {
    id: 26,
    artist: "Miles Davis",
    name: "In a Silent Way",
    year: "1969",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 27,
    artist: "Miles Davis",
    name: "Get Up With It",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 28,
    artist: "Dead Moon",
    name: "Dead Ahead",
    year: "2004",
    notes: "",
    price: "20",
    cover: "",
  },
  {
    id: 29,
    artist: "Bob Dylan",
    name: "Highway 61 Revisited",
    year: "1965",
    notes: "",
    price: "50",
    cover: "",
  },
  {
    id: 30,
    artist: "Brian Eno",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 31,
    artist: "Brian Eno",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 32,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 33,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 34,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 35,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 36,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
  {
    id: 37,
    artist: "David Axelrod",
    name: "Heavy Axe",
    year: "1974",
    notes: "",
    price: "100",
    cover: "",
  },
];
