export const artists = [
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: ["Fusion", "Jazz", "R&B"],
  },
  {
    id: 2,
    name: "Matt Baldwin",
    image: "",
    bio: "",
    genres: ["Instrumental", "Folk"],
  },
  {
    id: 3,
    name: "The Beatles",
    image: "",
    bio: "",
    genres: ["Rock", "Pop"],
  },
  {
    id: 4,
    name: "The Black Heart Procession",
    image: "",
    bio: "",
    genres: ["Indie Rock", "Rock"],
  },
  {
    id: 5,
    name: "Black Moth Super Rainbow",
    image: "",
    bio: "",
    genres: ["Indie Rock", "Instrumental", "Experimental"],
  },
  {
    id: 6,
    name: "Black Sabbath",
    image: "",
    bio: "",
    genres: ["Rock", "Metal"],
  },
  {
    id: 7,
    name: "David Bowie",
    image: "",
    bio: "",
    genres: ["Rock", "Pop", "Glam"],
  },
  {
    id: 8,
    name: "Broadcast",
    image: "",
    bio: "",
    genres: ["Indie Rock", "Soundtrack", "Experimental"],
  },
  {
    id: 9,
    name: "Arthur Brown's Kingdome Come",
    image: "",
    bio: "",
    genres: ["Rock", "Psychedelic"],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
  {
    id: 1,
    name: "David Axelrod",
    image: "",
    bio: "",
    genres: [],
  },
];
